import { defineConfig } from 'vite';
import { execSync } from 'node:child_process';
import { readFileSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { LIVE_SOURCE_DEFS } from './src/live-sources.js';

let rev = 'dev';
try {
  rev = execSync('git rev-parse --short HEAD').toString().trim();
} catch {
  /* no git — keep 'dev' */
}

const here = (p) => fileURLToPath(new URL(p, import.meta.url));
const SITE = 'https://second-corridor.vercel.app';

// R16+R18 — machine-readable trust, injected at build so it always matches
// the committed data: JSON-LD Article + one Dataset node per published file
// (Dataset markup reaches Google Dataset Search), and freshness meta.
function headInjection() {
  return {
    name: 'second-corridor-head-injection',
    transformIndexHtml: {
      order: 'pre',
      handler(html, ctx) {
        if (!/(^|[\\/])index\.html$/.test(ctx.filename)) return html;
        const datasets = [];
        let latest = '';
        for (const d of LIVE_SOURCE_DEFS) {
          const p = here(`public/data/${d.dataset}.json`);
          if (!existsSync(p)) continue;
          const prov = JSON.parse(readFileSync(p, 'utf8')).provenance;
          if (prov.retrievedAt > latest) latest = prov.retrievedAt;
          datasets.push({
            '@type': 'Dataset',
            name: d.title,
            description: `${d.title} — derived aggregate published by The Second Corridor. ${prov.vintage}.`,
            url: `${SITE}/methods#data`,
            license: 'https://creativecommons.org/licenses/by/4.0/',
            isAccessibleForFree: true,
            creator: { '@type': 'Person', name: 'Alex', email: 'Alex@ozarkintelligence.com' },
            temporalCoverage: prov.vintage,
            isBasedOn: d.url,
            dateModified: prov.retrievedAt,
            distribution: [
              {
                '@type': 'DataDownload',
                encodingFormat: 'application/json',
                contentUrl: `${SITE}/data/${d.dataset}.json`,
              },
              {
                '@type': 'DataDownload',
                encodingFormat: 'text/csv',
                contentUrl: `${SITE}/data/csv/${d.dataset}.csv`,
              },
            ],
          });
        }
        const article = {
          '@context': 'https://schema.org',
          '@graph': [
            {
              '@type': 'Article',
              headline: "The Second Corridor — New York's semiconductor buildout, 2022–2045",
              description:
                "Tracking New York's semiconductor buildout — investment, jobs, and the talent pipeline, from public data. Every number cited, estimates labeled.",
              author: { '@type': 'Person', name: 'Alex', email: 'Alex@ozarkintelligence.com' },
              mainEntityOfPage: `${SITE}/`,
              url: `${SITE}/`,
              image: `${SITE}/og.png`,
              datePublished: '2026-06-10',
              dateModified: latest,
              license: 'https://creativecommons.org/licenses/by/4.0/',
            },
            ...datasets,
          ],
        };
        const tags = [
          `<meta property="og:updated_time" content="${latest}" />`,
          `<meta name="last-modified" content="${latest}" />`,
          `<script type="application/ld+json">${JSON.stringify(article)}</script>`,
        ].join('\n    ');
        return html.replace('</head>', `    ${tags}\n  </head>`);
      },
    },
  };
}

export default defineConfig({
  define: {
    __BUILD_REV__: JSON.stringify(rev),
  },
  plugins: [headInjection()],
  build: {
    // F15: explicit target — the default is conservative; es2022 matches the
    // browsers this site supports and ships fewer transpiled helpers
    target: 'es2022',
    rollupOptions: {
      input: {
        index: here('index.html'),
        methods: here('methods.html'),
        decisions: here('decisions.html'),
        // generated by scripts/build-pages.mjs before vite runs
        ...(existsSync(here('changelog.html')) ? { changelog: here('changelog.html') } : {}),
      },
    },
  },
});
