// qa/print.mjs — F48≡R26: the print path is a first-class artifact (the
// brief), so it gets a smoke test + timing. Renders the BUILT site through
// the @media print stylesheet via headless page.pdf().
//
//   node qa/print.mjs            smoke test → qa/shots/brief.pdf (gitignored)
//   node qa/print.mjs --publish  also write public/brief.pdf — the linked
//                                artifact (committed; regenerated by the
//                                refresh workflow so the linked brief always
//                                carries current data)
//
// Asserts: render completes inside the budget, the PDF is a real multi-page
// document, and the frozen print header rendered.
import { spawn } from 'node:child_process';
import { writeFileSync, mkdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { chromium } from 'playwright';

const PUBLISH = process.argv.includes('--publish');
const PORT = 5301;
const BASE = `http://localhost:${PORT}`;
const RENDER_BUDGET_MS = 30000;

const dir = (p) => fileURLToPath(new URL(p, import.meta.url));
mkdirSync(dir('./shots/'), { recursive: true });

/* ---------- serve dist ---------- */
const server = spawn('npx', ['vite', 'preview', '--port', String(PORT), '--strictPort'], {
  shell: true,
  stdio: 'ignore',
});
async function up() {
  try { return (await fetch(BASE, { signal: AbortSignal.timeout(1500) })).ok; }
  catch { return false; }
}
for (let i = 0; i < 40 && !(await up()); i++) await new Promise((r) => setTimeout(r, 500));
if (!(await up())) { server.kill(); throw new Error('vite preview did not start'); }

let failed = false;
const fail = (msg) => { failed = true; console.error('PRINT FAIL: ' + msg); };

const browser = await chromium.launch();
const page = await browser.newPage({
  viewport: { width: 1280, height: 1400 },
  reducedMotion: 'reduce',
});
await page.goto(`${BASE}/?nointro`, { waitUntil: 'networkidle' });
await page.evaluate(() => document.fonts.ready);
await page.waitForTimeout(500);
// settle F28's offscreen-gated surfaces before printing (beforeprint also
// flushes them for real Ctrl+P users, but CDP printToPDF may not fire it)
await page.evaluate(async () => {
  for (let y = 0; y < document.body.scrollHeight; y += 800) {
    window.scrollTo(0, y);
    await new Promise((r) => setTimeout(r, 30));
  }
  window.scrollTo(0, 0);
});
await page.waitForTimeout(300);

const header = await page.evaluate(() => document.getElementById('print-header')?.textContent || '');
if (!/PRINTED AT YEAR \d{4}/.test(header)) fail(`print header not populated: "${header.slice(0, 60)}"`);

const t0 = Date.now();
const pdf = await page.pdf({
  format: 'Letter',
  printBackground: true,
  margin: { top: '12mm', bottom: '12mm', left: '10mm', right: '10mm' },
});
const ms = Date.now() - t0;

await browser.close();
server.kill();

const pages = (pdf.toString('latin1').match(/\/Type\s*\/Page[^s]/g) || []).length;
console.log(`brief rendered: ${(pdf.length / 1024).toFixed(0)} KB · ~${pages} pages · ${ms}ms`);
if (ms > RENDER_BUDGET_MS) fail(`print render took ${ms}ms (> ${RENDER_BUDGET_MS}ms budget)`);
if (pdf.length < 50_000) fail(`PDF suspiciously small (${pdf.length} B) — did the page render?`);
if (pages < 5) fail(`only ~${pages} pages — sections are missing from the print path`);

writeFileSync(dir('./shots/brief.pdf'), pdf);
if (PUBLISH) {
  writeFileSync(dir('../public/brief.pdf'), pdf);
  console.log('published → public/brief.pdf');
}

if (failed) process.exit(1);
console.log('print path clean');
process.exit(0);
